language: go

go:
  - "1.17.x"

go_import_path: github.com/devopsext/tools

before_install:
  - env GO111MODULE=on

install:
  - go get -t -v ./ ./cmd

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./ ./cmd
  - go build ./ ./cmd

after_success:
  - bash <(curl -s https://codecov.io/bash)